application/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware('auth')->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::prefix('clases')->name('clases.')->group(function () {
        Route::get('/', 'ClaseController@index')->name('index');
        Route::get('show/{id}', 'ClaseController@show')->name('show');
        Route::get('create', 'ClaseController@create')->name('create');
        Route::get('getin', 'ClaseController@getin')->name('getin');
        Route::post('join', 'ClaseController@join')->name('join');
        Route::post('store', 'ClaseController@store')->name('store');
        Route::get('edit/{id}', 'ClaseController@edit')->name('edit');
        Route::post('update/{id}', 'ClaseController@update')->name('update');
        Route::get('delete/{id}', 'ClaseController@delete')->name('delete');

        Route::prefix('{claseid}/tareas')->name('tareas.')->group(function () {
            Route::get('show/{id}', 'TareaController@show')->name('show');
            Route::get('create', 'TareaController@create')->name('create');
            Route::post('store', 'TareaController@store')->name('store');
            Route::get('edit/{id}', 'TareaController@edit')->name('edit');
            Route::post('update/{id}', 'TareaController@update')->name('update');
            Route::get('delete/{id}', 'TareaController@destroy')->name('delete');

            Route::prefix('{tareaid}/respuestas')->name('respuestas.')->group(function () {
                Route::get('ver', 'RespuestaController@ver')->name('ver');
                Route::post('store/{id?}', 'RespuestaController@store')->name('store');
                Route::get('edit/{id?}', 'RespuestaController@edit')->name('edit');
                Route::get('download/{id}', 'RespuestaController@download')->name('download');
            });
        });
    });
});

Auth::routes();

application/resources/views/layouts/principal.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ mix('js/app.js') }}" defer></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ mix('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">

        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    Sentence.me
                </a>
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('clases.index')}}">Mis Clases</a>
                    </li>
                </ul>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="miperfil">
                                        Mi Perfil
                                    </a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>
        @if($message=Session::get('message'))
            <div class="alert alert-info alert-block">
	            <button type="button" class="close" data-dismiss="alert">×</button>	
	            <strong>{{ $message }}</strong>
            </div>
        @endif
        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>