application/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware('auth')->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::prefix('clases')->name('clases.')->group(function () {
        Route::get('/', 'ClaseController@index')->name('index');
        Route::get('show/{id}', 'ClaseController@show')->name('show');
        Route::get('create', 'ClaseController@create')->name('create');
        Route::get('getin', 'ClaseController@getin')->name('getin');
        Route::post('join', 'ClaseController@join')->name('join');
        Route::post('store', 'ClaseController@store')->name('store');
        Route::get('edit/{id}', 'ClaseController@edit')->name('edit');
        Route::post('update/{id}', 'ClaseController@update')->name('update');
        Route::get('delete/{id}', 'ClaseController@delete')->name('delete');

        Route::prefix('{claseid}/tareas')->name('tareas.')->group(function () {
            Route::get('show/{id}', 'TareaController@show')->name('show');
            Route::get('create', 'TareaController@create')->name('create');
            Route::post('store', 'TareaController@store')->name('store');
            Route::get('edit/{id}', 'TareaController@edit')->name('edit');
            Route::post('update/{id}', 'TareaController@update')->name('update');
            Route::get('delete/{id}', 'TareaController@destroy')->name('delete');

            Route::prefix('{tareaid}/respuestas')->name('respuestas.')->group(function () {
                Route::get('ver', 'RespuestaController@ver')->name('ver');
                Route::post('store/{id?}', 'RespuestaController@store')->name('store');
                Route::get('edit/{id?}', 'RespuestaController@edit')->name('edit');
                Route::get('download/{id}', 'RespuestaController@download')->name('download');
            });
        });
    });
});

Auth::routes();

application/app/Clase.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Clase extends Model
{
    protected $fillable = ['nombre', 'descripcion', 'clave'];

    public function Users()
    {
        return $this->belongsToMany('App\User');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function tareas()
    {
        return $this->hasMany('App\Tarea');
    }

    public static function boot()
    {
        parent::boot();

        static::deleting(function ($clase) {
            $clase->Users()->detach();
            $clase->tareas()->delete();
        });
    }
}

application/app/Http/Controllers/ClaseController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\ClaseRepositoryInterface;
use App\Repositories\TareaRepositoryInterface;
use App\Repositories\UserRepositoryInterface;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\View;

class ClaseController extends Controller
{
    public function __construct(ClaseRepositoryInterface $clase, UserRepositoryInterface $user, TareaRepositoryInterface $tarea)
    {
        $this->clase = $clase;
        $this->user = $user;
        $this->tarea = $tarea;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clases = $this->clase->getuserclases(Auth::user());

        return View::make('clase.index')
            ->with('clases', $clases);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::user()->hasRole('Profesor')) {
            return View::make('clase.create');
        } else {
            return redirect(route('clases.index'))->with('error', 'No Tienes permitido Crear una clase');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (Auth::user()->hasRole('Profesor')) {
            $this->clase->create($request->toArray());
            $request->session()->flash('message', 'Clase Creada!');

            return redirect(route('clases.index'));
        } else {
            $request->session()->flash('message', 'No Tienes permitido Crear una clase');

            return redirect(route('clases.index'));
        }
    }

    public function getin()
    {
        return View::make('clase.join');
    }

    public function join(Request $request)
    {
        if (Auth::user()->hasRole('Alumno')) {
            if (count(Auth::user()->clases()->where('clave', $request->clave)->get()) < 1) {
                if ($this->clase->join($request)) {
                    $request->session()->flash('message', 'Te has unido A la clase :)');

                    return redirect(route('clases.index'));
                } else {
                    $request->session()->flash('message', 'No se ha encontrado la clase.');

                    return redirect(route('clases.getin'));
                }
            } else {
                $request->session()->flash('message', 'Ya perteneces a esa clase.');

                return redirect(route('clases.index'));
            }
        } else {
            $request->session()->flash('message', 'Solo alumnos pueden unirse');

            return redirect(route('clases.index'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $clase = $this->clase->getClase($id);
        $tareas = $this->tarea->getTareas($clase);

        return View::make('clase.show', ['tareas' => $tareas, 'clase' => $clase]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Auth::user()->hasRole('Profesor')) {
            $clase = $this->clase->getClase($id);

            return View::make('clase.edit', ['clase' => $clase]);
        } else {
            return redirect(route('clases.index'))->with('error', 'No Tienes permitido editar una clase');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int                      $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (Auth::user()->hasRole('Profesor')) {
            $clase = $this->clase->update($request->toArray(), $id);
            $request->session()->flash('message', 'Clase Actualizada');

            return redirect(route('clases.show', $id));
        } else {
            $request->session()->flash('message', 'No Tienes permitido actualizar una clase');

            return redirect(route('clases.index'));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function delete($id, Request $request)
    {
        if (Auth::user()->hasRole('Profesor')) {
            $this->clase->destroy($id);
            $request->session()->flash('message', 'Clase Borrada');

            return redirect(route('clases.index'));
        } else {
            $request->session()->flash('message', 'No Tienes permitido Borrar una clase');

            return redirect(route('clases.index'));
        }
    }
}

application/resources/views/clase/create.blade.php
@extends('layouts.principal')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Crear Clase') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('clases.store') }}">
                        @csrf
                        <div class="form-group row">
                            <label for="nombre" class="col-md-4 col-form-label text-md-right">Nombre</label>

                            <div class="col-md-6">
                                <input id="nombre" type="text" class="form-control" name="nombre" value="{{ old('nombre') }}" required autocomplete="nombre" autofocus>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="descripcion" class="col-md-4 col-form-label text-md-right"> Descripción</label>

                            <div class="col-md-6">
                                <textarea name="descripcion" class="form-control" rows="5" id="descripcion"></textarea>
                            </div>
                        </div>
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Crear') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

application/resources/views/clase/edit.blade.php
@extends('layouts.principal')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Editar Clase') }}</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('clases.update',$clase->id) }}">
                        @csrf
                        <div class="form-group row">
                            <label for="nombre" class="col-md-4 col-form-label text-md-right">Nombre</label>

                            <div class="col-md-6">
                                <input id="nombre" type="text" class="form-control" name="nombre" value="{{$clase->nombre}}" required autocomplete="nombre" autofocus>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="descripcion" class="col-md-4 col-form-label text-md-right"> Descripción</label>

                            <div class="col-md-6">
                                <textarea name="descripcion" class="form-control" rows="5" id="descripcion">
                                    {{{$clase->descripcion}}}
                                </textarea>
                            </div>
                        </div>
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Actualizar') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

application/resources/views/clase/index.blade.php
@extends('layouts.principal')

@section('content')

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            @hasrole('Profesor')
            <a href="{{route('clases.create')}}" class="btn btn-primary btn-lg w-100"  role="button" aria-disabled="true">Crear Clase</a>
            @else
            <a href="{{route('clases.getin')}}" class="btn btn-primary btn-lg w-100"  role="button" aria-disabled="true">Unirse A Clase</a>
            @endhasrole
        </div>
        <div class="col-12 mt-3">
            <div class="card">
            <h5 class="card-header">Clases</h5>
            <div class="card-body">
            @if (count($clases)>0)
                @foreach ($clases as $clase)
                    <div class="card">
                    <h5 class="card-header">{{$clase->nombre}}</h5>
                        <div class="card-body">
                            <p>{{$clase->descripcion}}</p>
                            <a href="{{route('clases.show',$clase->id)}}" class="btn btn-primary">Ver Clase</a> 
                        </div>
                    </div>
                @endforeach
            @else
                <p>No tienes Ninguna Clase</p>
            @endif
            </div>
            </div>
        </div>
    </div>
</div>
@stop

application/resources/views/clase/join.blade.php
@extends('layouts.principal')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Unirse A  Clase') }}</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('clases.join') }}">
                        @csrf
                        <div class="form-group row">
                            <label for="clave" class="col-md-4 col-form-label text-md-right">Introduca la Clave</label>

                            <div class="col-md-6">
                                <input id="clave" type="text" class="form-control" name="clave" value="" required autofocus maxlength="16" minlength="16" >
                            </div>
                        </div>
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Unirse') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@stop

application/resources/views/clase/show.blade.php
@extends('layouts.principal')

@section('content')
<div class="container-fluid">
    <div class="row">
        @hasrole('Profesor')
        <div class="col-4">
        <a href="{{route('clases.tareas.create',$clase->id)}}" class="btn btn-primary btn-lg w-100"  role="button" aria-disabled="true">Crear Tarea</a>
        </div>
        <div class="col-4">
        <a href="{{route('clases.edit',$clase->id)}}" class="btn btn-primary btn-lg w-100"  role="button" aria-disabled="true">Editar Clase</a>
        </div>
        <div class="col-4">
        <a href="{{route('clases.delete',$clase->id)}}" class="btn btn-primary btn-lg w-100"  role="button" aria-disabled="true">Borrar Clase</a>
        </div>
        <div class="col-12 text-center">
        <h1>Clave: <span class="badge badge-secondary ">{{$clase->clave}}</span></h1>
        </div>
        @endhasrole
        <div class="col-12 mt-3">
            <div class="card">
            <h5 class="card-header">Tareas</h5>
            <div class="card-body">
            @if (count($tareas)>0)
                @foreach ($tareas as $tarea)
                    <div class="card">
                    <h5 class="card-header">{{{$tarea->nombre}}}</h5>
                        <div class="card-body">
                            <p>{{$tarea->descripcion}}</p>
                            <a href="{{route('clases.tareas.show',[$clase->id,$tarea->id])}}" class="btn btn-primary">Ver Tarea</a> 
                           @hasrole('Profesor') 
                           <a href="{{route('clases.tareas.edit',[$clase->id,$tarea->id])}}" class="btn btn-primary">Editar Tarea</a> 
                           <a href="{{route('clases.tareas.delete',[$clase->id,$tarea->id])}}" class="btn btn-primary">Borrar Tarea</a> 
                           @endhasrole
                        </div>
                    </div>
                @endforeach
            @else
                <p>No tienes Ninguna Tarea</p>
            @endif
            </div>
            </div>
        </div>
        </div>
</div>
@stop