application/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware('auth')->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::prefix('clases')->name('clases.')->group(function () {
        Route::get('/', 'ClaseController@index')->name('index');
        Route::get('show/{id}', 'ClaseController@show')->name('show');
        Route::get('create', 'ClaseController@create')->name('create');
        Route::get('getin', 'ClaseController@getin')->name('getin');
        Route::post('join', 'ClaseController@join')->name('join');
        Route::post('store', 'ClaseController@store')->name('store');
        Route::get('edit/{id}', 'ClaseController@edit')->name('edit');
        Route::post('update/{id}', 'ClaseController@update')->name('update');
        Route::get('delete/{id}', 'ClaseController@delete')->name('delete');

        Route::prefix('{claseid}/tareas')->name('tareas.')->group(function () {
            Route::get('show/{id}', 'TareaController@show')->name('show');
            Route::get('create', 'TareaController@create')->name('create');
            Route::post('store', 'TareaController@store')->name('store');
            Route::get('edit/{id}', 'TareaController@edit')->name('edit');
            Route::post('update/{id}', 'TareaController@update')->name('update');
            Route::get('delete/{id}', 'TareaController@destroy')->name('delete');

            Route::prefix('{tareaid}/respuestas')->name('respuestas.')->group(function () {
                Route::get('ver', 'RespuestaController@ver')->name('ver');
                Route::post('store/{id?}', 'RespuestaController@store')->name('store');
                Route::get('edit/{id?}', 'RespuestaController@edit')->name('edit');
                Route::get('download/{id}', 'RespuestaController@download')->name('download');
            });
        });
    });
});

Auth::routes();

application/app/Respuesta.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

class Respuesta extends Model implements HasMedia
{
    protected $fillable = ['aprobado'];

    use HasMediaTrait;

    public function tarea()
    {
        return $this->belongsTo('App\Tarea');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

application/app/Http/Controllers/RespuestaController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\RespuestaRepositoryInterface;
use App\Repositories\TareaRepositoryInterface;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\View;

class RespuestaController extends Controller
{
    public function __construct(TareaRepositoryInterface $tarea, RespuestaRepositoryInterface $respuesta)
    {
        $this->tarea = $tarea;
        $this->respuesta = $respuesta;
    }

    public function edit($claseid, $tareaid, $respuestaid = null)
    {
        if (!Auth::user()->hasRole('Profesor')) {
            return View::make('respuesta.edit', ['claseid' => $claseid, 'tareaid' => $tareaid, 'respuestaid' => $respuestaid]);
        } else {
            return redirect(route('clases.show', $claseid))->with('error', 'No Tienes permitido editar una Tarea');
        }
    }

    public function store(Request $request, $claseid, $tareaid, $id = null)
    {
        if (Auth::user()->hasRole('Alumno')) {
            $tarea = $this->tarea->getTarea($tareaid);
            if ($id === null) {
                $respuesta = $this->respuesta->saveRespuesta($tarea);
                $respuesta = $this->respuesta->associateFile($request, $respuesta);
                $this->respuesta->comprobar($respuesta);
                $request->session()->flash('message', 'Respuesta Subida');

                return redirect(route('clases.tareas.show', [$claseid, $tareaid]));
            } else {
                $respuesta = $this->respuesta->getRespuesta($id);
                $respuesta = $this->respuesta->borrarRespuesta($respuesta);
                $respuesta = $this->respuesta->saveRespuesta($tarea);
                $respuesta = $this->respuesta->associateFile($request, $respuesta);
                $this->respuesta->comprobar($respuesta);
                $request->session()->flash('message', 'Respuesta Actualizada');

                return redirect(route('clases.tareas.show', [$claseid, $tareaid]));
            }
        }
    }

    public function ver($claseid, $tareaid)
    {
        if (Auth::user()->hasRole('Profesor')) {
            $respuestas = $this->tarea->getRespuestas($tareaid);

            return View::make('respuesta.ver', ['respuestas'=>$respuestas, 'claseid'=>$claseid, 'tareaid'=>$tareaid]);
        }
    }

    public function download($claseid, $tareaid, $respuestaid)
    {
        if (Auth::user()->hasRole('Profesor')) {
            $respuesta = $this->respuesta->getRespuesta($respuestaid);
            $media = $respuesta->getFirstMedia();

            return $media;
        }
    }
}

application/resources/views/respuesta/edit.blade.php
@extends('layouts.principal')

@section('content')
<form action="{{ route('clases.tareas.respuestas.store',[$claseid,$tareaid,$respuestaid]) }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label for="respuesta">Selecciona fichero</label>
            <input type="file" class="form-control-file" id="respuesta" name='respuesta'>
        </div>
        <input type="submit">
</form>

@stop

application/resources/views/respuesta/ver.blade.php
@extends('layouts.principal')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-6"><a href="{{route('clases.tareas.show',[$claseid,$tareaid])}}" class="btn btn-primary btn-lg" >Volver</a>
                </div>
        <div class="col-12">
            @if(count($respuestas)>0)
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Usuario</th>
                    <th scope="col">Resultado</th>
                    <th scope="col">Fichero</th>
                </tr>
            </thead>
            <tbody>
                @foreach($respuestas as $respuesta)
                <tr>
                    <th scope="row">{{$respuesta->user()->first()->id}}</th>
                    <td>{{$respuesta->user()->first()->name}}</td>
                    <td>
                        @if($respuesta->aprobado==1)
                        <strong>Aprobado</strong>
                        @else
                        <strong>Suspenso</strong>
                        @endif
                    </td>
                    <td><a href="{{route('clases.tareas.respuestas.download',[$claseid,$tareaid,$respuesta->id])}}" class="btn btn-primary btn-lg" role="button">Descargar</a></td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @else
        <h1>No tiene Respuestas</h1>
        @endif
        
        </div>
    </div>
</div>

@stop