application/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware('auth')->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::prefix('clases')->name('clases.')->group(function () {
        Route::get('/', 'ClaseController@index')->name('index');
        Route::get('show/{id}', 'ClaseController@show')->name('show');
        Route::get('create', 'ClaseController@create')->name('create');
        Route::get('getin', 'ClaseController@getin')->name('getin');
        Route::post('join', 'ClaseController@join')->name('join');
        Route::post('store', 'ClaseController@store')->name('store');
        Route::get('edit/{id}', 'ClaseController@edit')->name('edit');
        Route::post('update/{id}', 'ClaseController@update')->name('update');
        Route::get('delete/{id}', 'ClaseController@delete')->name('delete');

        Route::prefix('{claseid}/tareas')->name('tareas.')->group(function () {
            Route::get('show/{id}', 'TareaController@show')->name('show');
            Route::get('create', 'TareaController@create')->name('create');
            Route::post('store', 'TareaController@store')->name('store');
            Route::get('edit/{id}', 'TareaController@edit')->name('edit');
            Route::post('update/{id}', 'TareaController@update')->name('update');
            Route::get('delete/{id}', 'TareaController@destroy')->name('delete');

            Route::prefix('{tareaid}/respuestas')->name('respuestas.')->group(function () {
                Route::get('ver', 'RespuestaController@ver')->name('ver');
                Route::post('store/{id?}', 'RespuestaController@store')->name('store');
                Route::get('edit/{id?}', 'RespuestaController@edit')->name('edit');
                Route::get('download/{id}', 'RespuestaController@download')->name('download');
            });
        });
    });
});

Auth::routes();

application/app/Tarea.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tarea extends Model
{
    protected $fillable = ['nombre', 'descripcion'];

    public function clase()
    {
        return $this->belongsTo('App\Clase');
    }

    public function respuestas()
    {
        return $this->hasMany('App\Respuesta');
    }

    public function argumentos()
    {
        return $this->hasMany('App\Argumento');
    }

    public function solucion()
    {
        return $this->hasOne('App\Solucion');
    }

    public static function boot()
    {
        parent::boot();

        static::deleting(function ($tarea) {
            $tarea->argumentos()->delete();
            $tarea->respuestas()->delete();
            $tarea->solucion()->delete();
        });
    }
}

application/app/Http/Controllers/TareaController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\TareaRepositoryInterface;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\View;

class TareaController extends Controller
{
    public function __construct(TareaRepositoryInterface $tarea)
    {
        $this->tarea = $tarea;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($claseid)
    {
        if (Auth::user()->hasRole('Profesor')) {
            return View::make('tarea.create', ['claseid'=>$claseid]);
        } else {
            return redirect(route('clases.show', $claseid))->with('error', 'No Tienes permitido Crear una tarea');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $claseid)
    {
        if (Auth::user()->hasRole('Profesor')) {
            $this->tarea->create($request->toArray(), $claseid);

            return redirect(route('clases.show', $claseid))->with('message', 'Tarea Creada!');
        } else {
            return redirect(route('clases.index'))->with('error', 'No Tienes permitido Crear una Tarea');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($claseid, $tareaid)
    {
        $tarea = $this->tarea->getTarea($tareaid);
        $respuesta = $tarea->respuestas()->where('user_id', Auth::id())->first();
        $filename = '';
        if ($respuesta) {
            $filename = $respuesta->getFirstMedia()->name;
        }

        return View::make('tarea.show', ['tarea'=>$tarea, 'claseid'=>$claseid, 'filename'=>$filename, 'respuesta'=>$respuesta]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($claseid, $id)
    {
        if (Auth::user()->hasRole('Profesor')) {
            $tarea = $this->tarea->getTarea($id);
            $solucion = $tarea->solucion()->first()->solucion;
            $argumentos = [];
            foreach ($tarea->argumentos()->get() as $argumento) {
                array_push($argumentos, $argumento->argumento);
            }
            $argumentos = implode(',', $argumentos);

            return View::make('tarea.edit', ['claseid' => $claseid, 'tarea'=>$tarea, 'solucion'=>$solucion, 'argumentos'=>$argumentos]);
        } else {
            return redirect(route('clases.show', $claseid))->with('error', 'No Tienes permitido editar una Tarea');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int                      $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $claseid, $tareaid)
    {
        if (Auth::user()->hasRole('Profesor')) {
            $tarea = $this->tarea->update($request->toArray(), $tareaid);

            return redirect(route('clases.tareas.show', [$claseid, $tareaid]))->with('message', 'Tarea Actualizada');
        } else {
            return redirect(route('clases.index'))->with('error', 'No Tienes permitido actualizar una Tarea');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($claseid, $tareaid)
    {
        $this->tarea->destroy($tareaid);

        return redirect(route('clases.show', $claseid));
    }
}

application/resources/views/tarea/create.blade.php
@extends('layouts.principal')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Crear Tarea') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('clases.tareas.store',$claseid) }}">
                        @csrf
                        <div class="form-group row">
                            <label for="nombre" class="col-md-4 col-form-label text-md-right">Nombre</label>

                            <div class="col-md-6">
                                <input id="nombre" type="text" class="form-control" name="nombre" value="{{ old('nombre') }}" required  autofocus>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="descripcion" class="col-md-4 col-form-label text-md-right"> Descripción</label>

                            <div class="col-md-6">
                                <textarea name="descripcion" class="form-control" rows="5" id="descripcion"></textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="argumentos" class="col-md-4 col-form-label text-md-right">Argumentos separados por comas</label>

                            <div class="col-md-6">
                                <input id="argumentos" type="text" class="form-control" name="argumentos" value="{{ old('argumentos') }}" placeholder="1,2,3" required autofocus>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="solucion" class="col-md-4 col-form-label text-md-right">solucion</label>

                            <div class="col-md-6">
                                <input id="solucion" type="text" class="form-control" name="solucion" value="{{ old('solucion') }}" required  autofocus>
                            </div>
                        </div>
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Crear') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

application/resources/views/tarea/edit.blade.php
@extends('layouts.principal')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Editar Tarea') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('clases.tareas.update',[$claseid,$tarea->id]) }}">
                        @csrf
                        <div class="form-group row">
                            <label for="nombre" class="col-md-4 col-form-label text-md-right">Nombre</label>

                            <div class="col-md-6">
                            <input id="nombre" type="text" class="form-control" name="nombre" value="{{$tarea->nombre}}" required autocomplete="nombre" autofocus>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="descripcion" class="col-md-4 col-form-label text-md-right"> Descripción</label>

                            <div class="col-md-6">
                                <textarea name="descripcion" class="form-control" rows="5" id="descripcion">
                                    {{{$tarea->descripcion}}}
                                </textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="argumentos" class="col-md-4 col-form-label text-md-right">Argumentos separados por comas</label>

                            <div class="col-md-6">
                                <input id="argumentos" type="text" class="form-control" name="argumentos" value="{{ $argumentos }}" placeholder="1,2,3" required autofocus>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="solucion" class="col-md-4 col-form-label text-md-right">solucion</label>

                            <div class="col-md-6">
                                <input id="solucion" type="text" class="form-control" name="solucion" value="{{$solucion }}" required  autofocus>
                            </div>
                        </div>
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Editar') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

application/resources/views/tarea/show.blade.php
@extends('layouts.principal')

@section('content')
<div class="container-fluid">
    <div class="row">
        @hasrole('Profesor')
        <div class="col-4">
            <a href="{{route('clases.tareas.edit',[$claseid,$tarea->id])}}" class="btn btn-primary btn-lg w-100" role="button" aria-disabled="true">Editar Tarea</a>
        </div>
        <div class="col-4">
            <a href="{{route('clases.tareas.delete',[$claseid,$tarea->id])}}" class="btn btn-primary btn-lg w-100" role="button" aria-disabled="true">Borrar Tarea</a>
        </div>
        <div class="col-4">
            <a href="{{route('clases.tareas.respuestas.ver',[$claseid,$tarea->id])}}" class="btn btn-primary btn-lg w-100" role="button" aria-disabled="true">Ver Respuestas de Tarea</a>
        </div>
        @endhasrole
        <div class="col-12 mt-3">
            <div class="card">
                <h5 class="card-header">{{$tarea->nombre}}</h5>
                <div class="card-body">
                    <p>{{{$tarea->descripcion}}}</p>
                    @hasrole('Alumno')
                    <div class="row">
                        <div class="col-12 text-center mb-5">
                            <i class="fa fa-file" style="font-size: 30px; color: black;"></i>
                            <input type="text" value="{{$filename}}" disabled>
                        </div>
                        <div class="col-12">
                            @if(isset($respuesta))
                            <a href="{{route('clases.tareas.respuestas.edit',[$claseid,$tarea->id,$respuesta->id])}}" class="btn btn-primary btn-lg w-100" role="button" aria-disabled="true">Editar Respuesta</a>
                            @else
                            <a href="{{route('clases.tareas.respuestas.edit',[$claseid,$tarea->id])}}" class="btn btn-primary btn-lg w-100" role="button" aria-disabled="true">Editar Respuesta</a>
                            @endif
                        </div>
                    </div>
                    @endhasrole
                </div>
            </div>
        </div>
    </div>
</div>



@stop